-- Cria a tabela para armazenar os IPs autorizados
CREATE TABLE IF NOT EXISTS public.authorized_ips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_address TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ativa RLS (pode ser lido anonimamente para facilitar, ou por usuário autenticado)
ALTER TABLE public.authorized_ips ENABLE ROW LEVEL SECURITY;

-- Política para leitura (permitir que o app leia os IPs)
CREATE POLICY "Permitir leitura para todos" ON public.authorized_ips
FOR SELECT USING (true);

-- Insere os IPs que você já me passou como iniciais
INSERT INTO public.authorized_ips (ip_address, description)
VALUES 
    ('177.184.181.29', 'Loja 1'),
    ('177.184.190.27', 'Loja 2')
ON CONFLICT (ip_address) DO NOTHING;

COMMENT ON TABLE public.authorized_ips IS 'Lista de endereços IP autorizados a acessar o aplicativo.';
