-- Tabela Base de Produtos (Importada do Excel)
CREATE TABLE public.products_base (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    ean text, -- Coluna J (E.A.N.)
    description text, -- Coluna B (Descrição)
    internal_code text -- Coluna A (Código)
);

-- Habilitar RLS (Segurança)
ALTER TABLE public.products_base ENABLE ROW LEVEL SECURITY;

-- Política de Leitura (Todos podem consultar para buscar produtos)
CREATE POLICY "Enable Read Access for All"
ON public.products_base
FOR SELECT
TO anon, authenticated
USING (true);

-- Política de Escrita (Apenas autenticado/anon via painel pode inserir - simplificado para 'anon' por enquanto igual aos logs)
CREATE POLICY "Enable Insert/Update for Anon"
ON public.products_base
FOR ALL
TO anon
USING (true)
WITH CHECK (true);

-- Índices para deixar a busca rápida
CREATE INDEX idx_products_base_ean ON public.products_base (ean);
CREATE INDEX idx_products_base_description ON public.products_base USING gin(to_tsvector('portuguese', description));
