-- Create table for inventory logs
create table public.inventory_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  product_code text not null,
  quantity int not null,
  product_name text,
  user_id uuid references auth.users not null
);

-- Set up Row Level Security (RLS)
alter table public.inventory_logs enable row level security;

-- Policy: Users can insert their own logs
create policy "Users can insert their own logs"
on public.inventory_logs for insert
to authenticated
with check (auth.uid() = user_id);

-- Policy: Users can view their own logs (Optional, if they need history)
create policy "Users can view their own logs"
on public.inventory_logs for select
to authenticated
using (auth.uid() = user_id);

-- Policy: Admins/Managers can view all logs
-- (For simplicity in this step, we might allow authenticated to view all, 
-- or you can create a specific 'admin' role. For now, let's allow all authenticated to VIEW for the dashboard)
create policy "Enable read access for all users (Dashboard)"
on public.inventory_logs for select
to authenticated
using (true);
